###############################################

# Run GitHub's Super Linter against code base #

###############################################
---
name: GitHub's Super Linter
on: push
jobs:
    runs-on: ubuntu-latest
    name: GitHub's Super Linter
      steps:
          - name: Check out Git repository
          - uses: actions/checkout@master 
          - name: Run GitHub Super Linter
          - uses: github/super-linter@main
            env:
                VALIDATE_ALL_CODEBASE: true
                VALIDATE_JAVASCRIPT_STANDARD: false
                VALIDATE_JSCPD: false
                DEFAULT_BRANCH: main
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
